helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.com/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: dev-8de9b1fb5208bccacb14838fcfc47b35cd254bc5
    forcestring: true
  - name: VOTE.IMAGE
    value: harbor.canzhi.gkdevopscamp.com/vote/vote
    forcestring: true
  - name: VOTE.TAG
    value: dev-8de9b1fb5208bccacb14838fcfc47b35cd254bc5
    forcestring: true
  - name: WORKER.IMAGE
    value: harbor.canzhi.gkdevopscamp.com/vote/worker
    forcestring: true
  - name: WORKER.TAG
    value: dev-8de9b1fb5208bccacb14838fcfc47b35cd254bc5
    forcestring: true
