helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: staging-71c34cddbecc391944e80848995d33863714f5e8
    forcestring: true
  - name: VOTE.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/vote
    forcestring: true
  - name: VOTE.TAG
    value: latest
    forcestring: true
  - name: WORKER.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/worker
    forcestring: true
  - name: WORKER.TAG
    value: latest
    forcestring: true
