helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: main-08afe57ba7ec416db1eaaece370b01eaabf963fa
    forcestring: true
  - name: VOTE.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/vote
    forcestring: true
  - name: VOTE.TAG
    value: main-08afe57ba7ec416db1eaaece370b01eaabf963fa
    forcestring: true
  - name: WORKER.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/worker
    forcestring: true
  - name: WORKER.TAG
    value: main-08afe57ba7ec416db1eaaece370b01eaabf963fa
    forcestring: true
