helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: dev-c675c2c76131ed6abae49a92444c8d5a48185551
    forcestring: true
  - name: VOTE.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/vote
    forcestring: true
  - name: VOTE.TAG
    value: dev-c675c2c76131ed6abae49a92444c8d5a48185551
    forcestring: true
  - name: WORKER.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/worker
    forcestring: true
  - name: WORKER.TAG
    value: dev-c675c2c76131ed6abae49a92444c8d5a48185551
    forcestring: true
