helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: dev-3df9601283d780210861a10c68e8e21ae58842bf
    forcestring: true
  - name: VOTE.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/vote
    forcestring: true
  - name: VOTE.TAG
    value: dev-3df9601283d780210861a10c68e8e21ae58842bf
    forcestring: true
  - name: WORKER.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/worker
    forcestring: true
  - name: WORKER.TAG
    value: dev-3df9601283d780210861a10c68e8e21ae58842bf
    forcestring: true
