helm:
  parameters:
  - name: RESULT.IMAGE
    value: harbor.canzhi.gkdevopscamp.uk/vote/result
    forcestring: true
  - name: RESULT.TAG
    value: main-51e5f5cb60fc8c76e5b15fde11ad7dda9d40cbb0
    forcestring: true
